embeddings {
  tensor_name: "verification/embedding:00000"
  metadata_path: "00000/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00000/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00000/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00001"
  metadata_path: "00001/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00001/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00001/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00002"
  metadata_path: "00002/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00002/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00002/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00003"
  metadata_path: "00003/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00003/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00003/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00004"
  metadata_path: "00004/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00004/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00004/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00005"
  metadata_path: "00005/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00005/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00005/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00006"
  metadata_path: "00006/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00006/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00006/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00007"
  metadata_path: "00007/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00007/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00007/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00008"
  metadata_path: "00008/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00008/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00008/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00009"
  metadata_path: "00009/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00009/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00009/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00010"
  metadata_path: "00010/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00010/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00010/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00011"
  metadata_path: "00011/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00011/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00011/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00012"
  metadata_path: "00012/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00012/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00012/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00013"
  metadata_path: "00013/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00013/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00013/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00014"
  metadata_path: "00014/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00014/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00014/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00015"
  metadata_path: "00015/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00015/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00015/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00016"
  metadata_path: "00016/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00016/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00016/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00017"
  metadata_path: "00017/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00017/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00017/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00018"
  metadata_path: "00018/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00018/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00018/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00019"
  metadata_path: "00019/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00019/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00019/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00020"
  metadata_path: "00020/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00020/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00020/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00021"
  metadata_path: "00021/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00021/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00021/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00022"
  metadata_path: "00022/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00022/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00022/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00023"
  metadata_path: "00023/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00023/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00023/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00024"
  metadata_path: "00024/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00024/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00024/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00025"
  metadata_path: "00025/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00025/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00025/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00026"
  metadata_path: "00026/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00026/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00026/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00027"
  metadata_path: "00027/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00027/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00027/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00028"
  metadata_path: "00028/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00028/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00028/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00029"
  metadata_path: "00029/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00029/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00029/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00030"
  metadata_path: "00030/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00030/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00030/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00031"
  metadata_path: "00031/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00031/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00031/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00032"
  metadata_path: "00032/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00032/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00032/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00033"
  metadata_path: "00033/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00033/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00033/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00034"
  metadata_path: "00034/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00034/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00034/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00035"
  metadata_path: "00035/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00035/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00035/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00036"
  metadata_path: "00036/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00036/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00036/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00037"
  metadata_path: "00037/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00037/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00037/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00038"
  metadata_path: "00038/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00038/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00038/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00039"
  metadata_path: "00039/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00039/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00039/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00040"
  metadata_path: "00040/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00040/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00040/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00041"
  metadata_path: "00041/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00041/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00041/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00042"
  metadata_path: "00042/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00042/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00042/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00043"
  metadata_path: "00043/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00043/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00043/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00044"
  metadata_path: "00044/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00044/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00044/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00045"
  metadata_path: "00045/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00045/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00045/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00046"
  metadata_path: "00046/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00046/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00046/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00047"
  metadata_path: "00047/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00047/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00047/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00048"
  metadata_path: "00048/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00048/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00048/verification%2fembedding\\tensors.tsv"
}
embeddings {
  tensor_name: "verification/embedding:00049"
  metadata_path: "00049/verification%2fembedding\\metadata.tsv"
  sprite {
    image_path: "00049/verification%2fembedding\\sprite.png"
    single_image_dim: 128
    single_image_dim: 128
  }
  tensor_path: "00049/verification%2fembedding\\tensors.tsv"
}
